use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'AHFMKeywordVCServices_Example' do
  pod 'AHFMKeywordVCServices', :path => '../'

  target 'AHFMKeywordVCServices_Tests' do
    inherit! :search_paths

    
  end
end
